import { emptyAcademic } from "@/lib/documents/defaults";
import type { AcademicDocument, Publication } from "@/lib/schemas";

const pub = (p: Partial<Publication> & Pick<Publication, "id" | "kind" | "title" | "authors">): Publication => ({
  status: "published",
  year: "",
  venue: "",
  volume: "",
  issue: "",
  pages: "",
  editors: "",
  publisher: "",
  location: "",
  doi: "",
  url: "",
  ...p,
});

/** Fictional early-career academic — exercises every section, including author-name bolding. */
export function sampleAcademic(): AcademicDocument {
  const base = emptyAcademic();
  return {
    ...base,
    data: {
      header: {
        fullName: "Farhana Islam",
        designation: "Assistant Professor",
        department: "Department of Computer Science and Engineering",
        institution: "University of Dhaka",
        email: "farhana.islam@example.edu",
        phone: "+880 1712-000111",
        orcid: "0000-0002-1825-0097",
        googleScholar: "scholar.google.com/citations?user=abcd1234",
        researchGate: "researchgate.net/profile/Farhana-Islam",
        website: "farhanaislam.github.io",
      },
      authorAliases: ["Islam, F. N."],
      researchInterests: ["Natural language processing for low-resource languages", "Bangla speech recognition", "Fairness in machine learning", "Educational data mining"],
      education: [
        {
          id: "ed1",
          degree: "PhD",
          fieldOfStudy: "Computer Science",
          institution: "University of Toronto",
          location: "Toronto, Canada",
          period: { start: "2016-09", end: "2021-06", current: false },
          result: "",
          thesisTitle: "Transfer Learning for Low-Resource Speech Recognition: The Case of Bangla",
          supervisor: "Prof. Graeme Hirst",
        },
        {
          id: "ed2",
          degree: "BSc",
          fieldOfStudy: "Computer Science and Engineering",
          institution: "University of Dhaka",
          location: "Dhaka, Bangladesh",
          period: { start: "2011", end: "2015", current: false },
          result: "CGPA 3.91 / 4.00 (1st in class)",
          thesisTitle: "Rule-based Stemming for Bangla Text",
          supervisor: "Dr. Mohammad Kaykobad",
        },
      ],
      teaching: [
        {
          id: "t1",
          position: "Assistant Professor",
          organization: "University of Dhaka",
          location: "Dhaka",
          period: { start: "2021-09", end: "", current: true },
          bullets: [],
          courses: ["CSE 4101: Natural Language Processing (Fall 2021–present)", "CSE 2201: Data Structures (Spring 2022, 2023)", "CSE 6109: Advanced Machine Learning (graduate, 2024)"],
        },
        {
          id: "t2",
          position: "Teaching Assistant",
          organization: "University of Toronto",
          location: "Toronto",
          period: { start: "2017-01", end: "2020-12", current: false },
          bullets: ["Led weekly tutorials for 120+ undergraduates; received the departmental TA award (2019)."],
          courses: ["CSC 401: Natural Language Computing", "CSC 311: Introduction to Machine Learning"],
        },
      ],
      research: [
        {
          id: "r1",
          position: "Graduate Research Assistant",
          organization: "Computational Linguistics Lab, University of Toronto",
          location: "Toronto",
          period: { start: "2016-09", end: "2021-06", current: false },
          bullets: ["Built the first open 1,000-hour Bangla speech corpus with 312 speakers.", "Developed cross-lingual transfer methods cutting word error rate by 27% relative."],
          supervisor: "Prof. Graeme Hirst",
        },
      ],
      publications: [
        pub({
          id: "p1",
          kind: "journal",
          authors: [
            { family: "Islam", given: "Farhana" },
            { family: "Hirst", given: "Graeme" },
          ],
          year: "2023",
          title: "Cross-lingual transfer for low-resource speech recognition: Lessons from Bangla",
          venue: "Computational Linguistics",
          volume: "49",
          issue: "2",
          pages: "311–349",
          doi: "10.1162/coli_a_00471",
        }),
        pub({
          id: "p2",
          kind: "journal",
          authors: [
            { family: "Rahman", given: "Mahfuz" },
            { family: "Islam", given: "F. N." },
            { family: "Chowdhury", given: "Sadia" },
          ],
          year: "",
          status: "in-press",
          title: "Measuring gender bias in Bangla word embeddings",
          venue: "ACM Transactions on Asian and Low-Resource Language Information Processing",
        }),
        pub({
          id: "p3",
          kind: "conference",
          authors: [
            { family: "Islam", given: "Farhana" },
            { family: "Ahmed", given: "Tanvir" },
            { family: "Hirst", given: "Graeme" },
          ],
          year: "2022",
          title: "BanglaSpeech-1K: A large open corpus for Bangla automatic speech recognition",
          venue: "Proceedings of the 13th Language Resources and Evaluation Conference (LREC)",
          location: "Marseille, France",
          pages: "4412–4420",
          publisher: "European Language Resources Association",
        }),
        pub({
          id: "p4",
          kind: "chapter",
          authors: [{ family: "Islam", given: "Farhana" }],
          year: "2024",
          title: "Speech technology for South Asian languages",
          venue: "The Handbook of Language Technology in the Global South",
          editors: "S. Bird & M. Choudhury",
          publisher: "Springer",
          pages: "201–224",
        }),
        pub({
          id: "p5",
          kind: "preprint",
          authors: [
            { family: "Karim", given: "Nabila" },
            { family: "Islam", given: "Farhana" },
          ],
          year: "2025",
          title: "Few-shot dialect identification for Bangla with self-supervised speech models",
          venue: "arXiv",
          url: "arxiv.org/abs/2503.01234",
        }),
      ],
      grants: [
        {
          id: "g1",
          title: "Open speech technology for Bangla-speaking communities",
          funder: "Bangladesh Research Council (BRC)",
          role: "Principal Investigator",
          amount: "BDT 25,00,000",
          period: { start: "2023", end: "2026", current: false },
        },
        {
          id: "g2",
          title: "Google Research Scholar Program",
          funder: "Google",
          role: "Principal Investigator",
          amount: "USD 60,000",
          period: { start: "2024", end: "", current: false },
        },
      ],
      awards: [
        { id: "a1", title: "Best Paper Award", issuer: "LREC 2022", date: "2022-06", description: "" },
        { id: "a2", title: "Connaught International Scholarship", issuer: "University of Toronto", date: "2016", description: "Full funding for doctoral studies." },
        { id: "a3", title: "Prime Minister's Gold Medal", issuer: "University Grants Commission, Bangladesh", date: "2016", description: "" },
      ],
      presentations: [
        { id: "pr1", title: "Building speech technology when data is scarce", kind: "invited", event: "Bangla NLP Summit", location: "Dhaka, Bangladesh", date: "2024-12" },
        { id: "pr2", title: "BanglaSpeech-1K", kind: "talk", event: "LREC 2022", location: "Marseille, France", date: "2022-06" },
      ],
      service: [
        { id: "sv1", role: "Reviewer", organization: "ACL Rolling Review, Interspeech, IEEE/ACM TASLP", period: { start: "2020", end: "", current: true } },
        { id: "sv2", role: "Program Committee Member", organization: "BLP Workshop @ EMNLP", period: { start: "2023", end: "2024", current: false } },
      ],
      memberships: [
        { id: "m1", organization: "Association for Computational Linguistics (ACL)", role: "Member", period: { start: "2018", end: "", current: true } },
        { id: "m2", organization: "IEEE", role: "Member", period: { start: "2016", end: "", current: true } },
      ],
      skills: [
        { id: "s1", category: "Programming", items: ["Python", "PyTorch", "C++", "R"] },
        { id: "s2", category: "Software", items: ["Kaldi", "ESPnet", "Hugging Face Transformers", "LaTeX"] },
        { id: "s3", category: "Methods", items: ["Speech corpus design", "Crowdsourced annotation", "Statistical significance testing"] },
      ],
      referees: [
        {
          id: "ref1",
          name: "Prof. Graeme Hirst",
          designation: "Professor Emeritus",
          organization: "Department of Computer Science, University of Toronto",
          email: "gh@example.edu",
          phone: "",
          relationship: "PhD supervisor",
        },
        {
          id: "ref2",
          name: "Dr. Mohammad Kaykobad",
          designation: "Professor",
          organization: "Department of CSE, BRAC University",
          email: "kaykobad@example.edu",
          phone: "",
          relationship: "Undergraduate thesis supervisor",
        },
      ],
    },
  };
}
