import type { CommitteeLevel, ElectionResult, PoliticalSection } from "@/lib/schemas";
import { toBanglaDigits, type LabelLanguage } from "../biodata/labels";

const EN = {
  title: "Political CV",
  sections: {
    photo: "Photo",
    personal: "Personal Information",
    contact: "Contact Information",
    partyRole: "Party Position",
    nomination: "Nomination Sought",
    positions: "Political Career",
    elections: "Electoral Experience",
    movements: "Role in Movements",
    cases: "Political Cases & Imprisonment",
    education: "Educational Qualifications",
    occupation: "Profession",
    socialWork: "Social Work",
    declaration: "Declaration",
  } as Record<PoliticalSection, string>,
  fields: {
    fullName: "Name",
    fathersName: "Father's Name",
    mothersName: "Mother's Name",
    spouseName: "Spouse's Name",
    dateOfBirth: "Date of Birth",
    age: "Age",
    religion: "Religion",
    nid: "NID No.",
    presentAddress: "Present Address",
    permanentAddress: "Permanent Address",
    phone: "Mobile",
    email: "Email",
    facebook: "Facebook",
    party: "Party",
    position: "Current Position",
    committee: "Committee / Unit",
    memberSince: "Member Since",
    membershipNo: "Membership No.",
    election: "Election",
    constituency: "Constituency",
    area: "Area",
    symbol: "Election Symbol",
    place: "Place",
    date: "Date",
    signature: "Signature",
  },
  table: {
    position: "Position",
    organization: "Organisation / Committee",
    level: "Level",
    period: "Period",
    election: "Election",
    post: "Post",
    constituency: "Constituency",
    year: "Year",
    result: "Result",
    votes: "Votes",
    description: "Description",
    status: "Status",
    degree: "Exam / Degree",
    institution: "Institution",
    board: "Board / University",
    passingYear: "Passing Year",
    role: "Role",
  },
  level: { central: "Central", division: "Division", district: "District / Metro", upazila: "Upazila / Thana", union: "Union / Pourashava", ward: "Ward" } as Record<
    CommitteeLevel,
    string
  >,
  result: { won: "Won", lost: "Lost", withdrew: "Withdrew" } as Record<ElectionResult, string>,
  years: (n: number) => `${n} years`,
  running: "Running",
};

export type PoliticalLabels = typeof EN;

const BN: PoliticalLabels = {
  title: "রাজনৈতিক জীবনবৃত্তান্ত",
  sections: {
    photo: "ছবি",
    personal: "ব্যক্তিগত তথ্য",
    contact: "যোগাযোগ",
    partyRole: "দলীয় পদ",
    nomination: "মনোনয়ন প্রত্যাশা",
    positions: "রাজনৈতিক জীবন",
    elections: "নির্বাচনী অভিজ্ঞতা",
    movements: "আন্দোলন-সংগ্রামে ভূমিকা",
    cases: "রাজনৈতিক মামলা ও কারাবরণ",
    education: "শিক্ষাগত যোগ্যতা",
    occupation: "পেশা",
    socialWork: "সামাজিক কর্মকাণ্ড",
    declaration: "অঙ্গীকারনামা",
  },
  fields: {
    fullName: "নাম",
    fathersName: "পিতার নাম",
    mothersName: "মাতার নাম",
    spouseName: "স্বামী / স্ত্রীর নাম",
    dateOfBirth: "জন্ম তারিখ",
    age: "বয়স",
    religion: "ধর্ম",
    nid: "জাতীয় পরিচয়পত্র নং",
    presentAddress: "বর্তমান ঠিকানা",
    permanentAddress: "স্থায়ী ঠিকানা",
    phone: "মোবাইল",
    email: "ইমেইল",
    facebook: "ফেসবুক",
    party: "দল",
    position: "বর্তমান পদ",
    committee: "কমিটি / ইউনিট",
    memberSince: "সদস্য হওয়ার সাল",
    membershipNo: "সদস্য নং",
    election: "নির্বাচন",
    constituency: "নির্বাচনী এলাকা (আসন)",
    area: "এলাকা",
    symbol: "নির্বাচনী প্রতীক",
    place: "স্থান",
    date: "তারিখ",
    signature: "স্বাক্ষর",
  },
  table: {
    position: "পদ",
    organization: "সংগঠন / কমিটি",
    level: "স্তর",
    period: "সময়কাল",
    election: "নির্বাচন",
    post: "পদ",
    constituency: "এলাকা",
    year: "সাল",
    result: "ফলাফল",
    votes: "প্রাপ্ত ভোট",
    description: "বিবরণ",
    status: "বর্তমান অবস্থা",
    degree: "পরীক্ষা / ডিগ্রি",
    institution: "শিক্ষা প্রতিষ্ঠান",
    board: "বোর্ড / বিশ্ববিদ্যালয়",
    passingYear: "পাসের সন",
    role: "দায়িত্ব",
  },
  level: { central: "কেন্দ্রীয়", division: "বিভাগীয়", district: "জেলা / মহানগর", upazila: "উপজেলা / থানা", union: "ইউনিয়ন / পৌরসভা", ward: "ওয়ার্ড" },
  result: { won: "বিজয়ী", lost: "পরাজিত", withdrew: "প্রত্যাহার" },
  years: (n: number) => `${toBanglaDigits(String(n))} বছর`,
  running: "অধ্যয়নরত",
};

export const POLITICAL_LABELS: Record<LabelLanguage, PoliticalLabels> = { en: EN, bn: BN };
